import 'package:flutter/material.dart';

class LightThemeColor {
  static const Color primary = Color(0xffe53935); // Vivid red
  static const Color surfaceTint = Color(0xffe53935);
  static const Color onPrimary = Color(0xffffffff);
  static const Color primaryContainer = Color(0xffff8a80); // Light red
  static const Color onPrimaryContainer = Color(0xffb71c1c);
  static const Color secondary = Color(0xffd32f2f); // Deep red
  static const Color onSecondary = Color(0xffffffff);
  static const Color secondaryContainer = Color(0xffffcdd2); // Pale red
  static const Color onSecondaryContainer = Color(0xffb71c1c);
  static const Color tertiary = Color(0xfff44336); // Red accent
  static const Color onTertiary = Color(0xffffffff);
  static const Color tertiaryContainer = Color(0xffffebee); // Very light red
  static const Color onTertiaryContainer = Color(0xffb71c1c);
  static const Color error = Color(0xffd50000); // Vivid error red
  static const Color onError = Color(0xffffffff);
  static const Color errorContainer = Color(0xffff5252);
  static const Color onErrorContainer = Color(0xffb71c1c);
  static const Color surface = Color(0xfffff3f3); // Soft red-tinted white
  static const Color onSurface = Color(0xff1d1b20);
  static const Color onSurfaceVariant = Color(0xffb71c1c);
  static const Color outline = Color(0xffe57373); // Red outline
  static const Color outlineVariant = Color(0xffffcdd2);
  static const Color shadow = Color(0xffb71c1c);
  static const Color scrim = Color(0xffb71c1c);
  static const Color inverseSurface = Color(0xffb71c1c);
  static const Color inversePrimary = Color(0xffff8a80);
  static const Color primaryFixed = Color(0xffff8a80);
  static const Color onPrimaryFixed = Color(0xffb71c1c);
  static const Color primaryFixedDim = Color(0xffe57373);
  static const Color onPrimaryFixedVariant = Color(0xffb71c1c);
  static const Color secondaryFixed = Color(0xffffcdd2);
  static const Color onSecondaryFixed = Color(0xffb71c1c);
  static const Color secondaryFixedDim = Color(0xffe57373);
  static const Color onSecondaryFixedVariant = Color(0xffb71c1c);
  static const Color tertiaryFixed = Color(0xffffebee);
  static const Color onTertiaryFixed = Color(0xffb71c1c);
  static const Color tertiaryFixedDim = Color(0xfff44336);
  static const Color onTertiaryFixedVariant = Color(0xffb71c1c);
  static const Color surfaceDim = Color(0xffffebee);
  static const Color surfaceBright = Color(0xfffff3f3);
  static const Color surfaceContainerLowest = Color(0xffffffff);
  static const Color surfaceContainerLow = Color(0xffffebee);
  static const Color surfaceContainer = Color(0xffffcdd2);
  static const Color surfaceContainerHigh = Color(0xffff8a80);
  static const Color surfaceContainerHighest = Color(0xffe57373);
}

class DarkThemeColor {
  static const Color primary = Color(0xffe53935); // Vivid red
  static const Color surfaceTint = Color(0xffe53935);
  static const Color onPrimary = Color(0xffffffff);
  static const Color primaryContainer = Color(0xffb71c1c); // Dark red
  static const Color onPrimaryContainer = Color(0xffff8a80);
  static const Color secondary = Color(0xffd32f2f); // Deep red
  static const Color onSecondary = Color(0xffffffff);
  static const Color secondaryContainer = Color(0xffb71c1c);
  static const Color onSecondaryContainer = Color(0xffffcdd2);
  static const Color tertiary = Color(0xfff44336); // Red accent
  static const Color onTertiary = Color(0xffffffff);
  static const Color tertiaryContainer = Color(0xffb71c1c);
  static const Color onTertiaryContainer = Color(0xffffebee);
  static const Color error = Color(0xffd50000); // Vivid error red
  static const Color onError = Color(0xffffffff);
  static const Color errorContainer = Color(0xffb71c1c);
  static const Color onErrorContainer = Color(0xffff5252);
  static const Color surface = Color(0xff1a0000); // Deep red-tinted black
  static const Color onSurface = Color(0xffffebee);
  static const Color onSurfaceVariant = Color(0xffb71c1c);
  static const Color outline = Color(0xffe57373); // Red outline
  static const Color outlineVariant = Color(0xffb71c1c);
  static const Color shadow = Color(0xffb71c1c);
  static const Color scrim = Color(0xffb71c1c);
  static const Color inverseSurface = Color(0xffb71c1c);
  static const Color inversePrimary = Color(0xffff8a80);
  static const Color primaryFixed = Color(0xffb71c1c);
  static const Color onPrimaryFixed = Color(0xffff8a80);
  static const Color primaryFixedDim = Color(0xffe57373);
  static const Color onPrimaryFixedVariant = Color(0xffb71c1c);
  static const Color secondaryFixed = Color(0xffb71c1c);
  static const Color onSecondaryFixed = Color(0xffffcdd2);
  static const Color secondaryFixedDim = Color(0xffe57373);
  static const Color onSecondaryFixedVariant = Color(0xffb71c1c);
  static const Color tertiaryFixed = Color(0xffb71c1c);
  static const Color onTertiaryFixed = Color(0xffffebee);
  static const Color tertiaryFixedDim = Color(0xfff44336);
  static const Color onTertiaryFixedVariant = Color(0xffb71c1c);
  static const Color surfaceDim = Color(0xff1a0000);
  static const Color surfaceBright = Color(0xff3b383e);
  static const Color surfaceContainerLowest = Color(0xff0f0d13);
  static const Color surfaceContainerLow = Color(0xff1d1b20);
  static const Color surfaceContainer = Color(0xff211f24);
  static const Color surfaceContainerHigh = Color(0xff2c292f);
  static const Color surfaceContainerHighest = Color(0xff37343a);
}
