include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer: 
  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - "**/*.md"
    - "test/mock.mocks.dart"
    - '**/*.gr.dart'